/**
 * One-off golden regeneration helper for engine version bumps.
 *
 * Recomputes the two 100 000-tick soak hashes: the populated world's, which
 * lives in `fixtures/soakWorld.ts`, and the lifeless reference world's in
 * `environmentSoak.test.ts`.
 *
 * The populated config is IMPORTED rather than restated. It used to be a second
 * copy of the fixture's parameters here, which is exactly the kind of
 * duplication that regenerates a hash for a world nobody runs: when M14
 * enlarged the soak map, this script cheerfully reproduced the old 96-cell
 * hash and it took a failing test to notice. The 10 000-tick fixture checkpoints are
 * regenerated by `pnpm headless` instead — see goldenStateHashes.json.
 *
 * Run with: pnpm exec tsx scripts/regenerateSoakHashes.ts
 */
import { DEFAULT_CONFIG, SOAK_CONFIG, SimulationEngine, cloneConfig } from "@eon/engine";

function lifelessConfig() {
  const config = cloneConfig(DEFAULT_CONFIG);
  config.world.initialOrganisms = 0;
  return config;
}

const SEED = 0xe0a12026;
const TICKS = 100_000;

const which = process.argv[2] ?? "both";

if (which === "populated" || which === "both") {
  const engine = new SimulationEngine({ seed: SEED, config: SOAK_CONFIG });
  const startedAt = Date.now();
  engine.stepMany(TICKS);
  console.log(
    `populated soak (soak.test.ts GOLDEN_SOAK_HASH): ${engine.computeStateHash()} ` +
      `(pop ${engine.organisms.liveCount}, species ${engine.species.count}, ` +
      `events ${engine.events.events.length}, ${Math.round((Date.now() - startedAt) / 1000)}s)`,
  );
}

if (which === "lifeless" || which === "both") {
  const engine = new SimulationEngine({ seed: SEED, config: lifelessConfig() });
  const startedAt = Date.now();
  engine.stepMany(TICKS);
  console.log(
    `environment soak (environmentSoak.test.ts GOLDEN_SOAK_HASH): ${engine.computeStateHash()} ` +
      `(${Math.round((Date.now() - startedAt) / 1000)}s)`,
  );
}
