/**
 * One-off golden regeneration helper for engine version bumps.
 *
 * Recomputes the two 100 000-tick soak hashes that live as constants in
 * `soak.test.ts` (populated 64-grid world) and `environmentSoak.test.ts`
 * (lifeless reference world). The 10 000-tick fixture checkpoints are
 * regenerated by `pnpm headless` instead — see goldenStateHashes.json.
 *
 * Run with: pnpm exec tsx scripts/regenerateSoakHashes.ts
 */
import { DEFAULT_CONFIG, SimulationEngine, cloneConfig } from "@eon/engine";

function populatedSoakConfig() {
  const GRID = 96;
  const config = cloneConfig(DEFAULT_CONFIG);
  config.world.envGridSize = GRID;
  config.world.sizeLU = GRID * config.world.envCellSizeLU;
  config.world.generation.edgeFalloffCells = Math.max(1, Math.floor(GRID / 8));
  config.world.initialOrganisms = 64;
  config.world.founderSpawnRadiusLU = Math.min(
    config.world.founderSpawnRadiusLU,
    config.world.sizeLU / 4,
  );
  config.world.validity.minFounderRegionCells = Math.floor((GRID * GRID) / 8);
  config.world.validity.minTotalPlantCapacity = Math.floor(
    config.world.validity.minTotalPlantCapacity / 16,
  );
  return config;
}

function lifelessConfig() {
  const config = cloneConfig(DEFAULT_CONFIG);
  config.world.initialOrganisms = 0;
  return config;
}

const SEED = 0xe0a12026;
const TICKS = 100_000;

const which = process.argv[2] ?? "both";

if (which === "populated" || which === "both") {
  const engine = new SimulationEngine({ seed: SEED, config: populatedSoakConfig() });
  const startedAt = Date.now();
  engine.stepMany(TICKS);
  console.log(
    `populated soak (soak.test.ts GOLDEN_SOAK_HASH): ${engine.computeStateHash()} ` +
      `(pop ${engine.organisms.liveCount}, species ${engine.species.count}, ` +
      `events ${engine.events.events.length}, ${Math.round((Date.now() - startedAt) / 1000)}s)`,
  );
}

if (which === "lifeless" || which === "both") {
  const engine = new SimulationEngine({ seed: SEED, config: lifelessConfig() });
  const startedAt = Date.now();
  engine.stepMany(TICKS);
  console.log(
    `environment soak (environmentSoak.test.ts GOLDEN_SOAK_HASH): ${engine.computeStateHash()} ` +
      `(${Math.round((Date.now() - startedAt) / 1000)}s)`,
  );
}
